<?php

class toba_mc_comp__2343
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'catedras',
    'objeto' => 2343,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'dt_materias',
    'subclase_archivo' => 'datos/dt_materias.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'materias',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'catedras',
    'fuente' => 'catedras',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2024-09-27 11:30:48',
    'punto_montaje' => 13,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => NULL,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'materias',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => NULL,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => NULL,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => NULL,
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 886,
      'columna' => 'id_materia',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    1 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 887,
      'columna' => 'nombre_carrera',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    2 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 888,
      'columna' => 'nombre_materia',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    3 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 889,
      'columna' => 'ano_plan',
      'tipo' => 'E',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    4 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 890,
      'columna' => 'periodo_plan',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    5 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 891,
      'columna' => 'horas_totales',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    6 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 892,
      'columna' => 'horas_semanales',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    7 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 893,
      'columna' => 'depto_principal',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    8 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 894,
      'columna' => 'depto',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    9 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 895,
      'columna' => 'area',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    10 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 896,
      'columna' => 'orientacion',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    11 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 897,
      'columna' => 'contenidos_minimos',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    12 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 898,
      'columna' => 'correlativas_para_cursar',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    13 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 899,
      'columna' => 'correlativas_para_aprobar',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    14 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 900,
      'columna' => 'competencias',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    15 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 901,
      'columna' => 'optativa',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    16 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 902,
      'columna' => 'trayecto',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    17 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 903,
      'columna' => 'cod_carrera',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    18 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 904,
      'columna' => 'plan_guarani',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    19 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 905,
      'columna' => 'version_guarani',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    20 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 906,
      'columna' => 'plan_mocovi',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    21 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 907,
      'columna' => 'plan_ordenanzas',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    22 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 908,
      'columna' => 'cod_guarani',
      'tipo' => 'C',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
    23 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2343,
      'col_id' => 909,
      'columna' => 'observaciones',
      'tipo' => 'X',
      'pk' => NULL,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => NULL,
      'externa' => NULL,
      'tabla' => NULL,
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>