<?php

class toba_mc_comp__10
{
	static function get_metadatos()
	{
		return array (
  'molde' => 
  array (
    'proyecto' => 'catedras',
    'molde' => 10,
    'operacion_tipo' => 10,
    'nombre' => 'Aval Programas',
    'item' => '3472',
    'carpeta_archivos' => 'aval_programas',
    'prefijo_clases' => '_aval_programas',
    'fuente' => 'catedras',
    'clase' => 'toba_asistente_abms',
  ),
  'molde_abms' => 
  array (
    'proyecto' => 'catedras',
    'molde' => 10,
    'tabla' => 'programas',
    'gen_usa_filtro' => 0,
    'gen_separar_pantallas' => 1,
    'cuadro_eof' => NULL,
    'cuadro_id' => 'id_programa',
    'filtro_comprobar_parametros' => NULL,
    'cuadro_forzar_filtro' => NULL,
    'cuadro_eliminar_filas' => 0,
    'cuadro_carga_origen' => 'datos_tabla',
    'cuadro_carga_sql' => 'SELECT
	t_p.id_programa,
	t_p.id_designacion,
	t_p.id_asignacion,
	t_p.legajo_resp,
	t_p.dni_resp,
	t_p.apellido_resp,
	t_p.nombre_resp,
	t_p.cargo_resp,
	t_p.equipo_catedra,
	t_p.id_materia_prog,
	t_p.periodo_dictado,
	t_p.ano_academico,
	t_p.fundamentacion,
	t_p.objetivos,
	t_p.programa_analitico,
	t_p.bibliografia,
	t_p.propuesta_metodologica,
	t_p.evaluacion_acreditacion,
	t_p.distribucion_horaria,
	t_p.cronograma_tentativo,
	t_p.estado,
	t_p.observaciones,
	t_p.comentarios,
	t_p.firma_doc,
	t_p.firma_dto,
	t_p.firma_sac,
	t_p.horas_teoricas,
	t_p.horas_practicas,
	t_p.horas_teoricopracticas
FROM
	programas as t_p
ORDER BY apellido_resp',
    'cuadro_carga_php_include' => NULL,
    'cuadro_carga_php_clase' => NULL,
    'cuadro_carga_php_metodo' => NULL,
    'datos_tabla_validacion' => NULL,
    'apdb_pre' => NULL,
  ),
  'molde_abms_fila' => 
  array (
    0 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 153,
      'orden' => '1',
      'columna' => 'id_programa',
      'etiqueta' => 'Id Programa',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 1,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    1 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 154,
      'orden' => '2',
      'columna' => 'id_designacion',
      'etiqueta' => 'Id Designacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    2 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 155,
      'orden' => '3',
      'columna' => 'id_asignacion',
      'etiqueta' => 'Id Asignacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    3 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 156,
      'orden' => '4',
      'columna' => 'legajo_resp',
      'etiqueta' => 'Legajo Resp',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    4 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 157,
      'orden' => '5',
      'columna' => 'dni_resp',
      'etiqueta' => 'Dni Resp',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    5 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 158,
      'orden' => '6',
      'columna' => 'apellido_resp',
      'etiqueta' => 'Apellido Resp',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    6 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 159,
      'orden' => '7',
      'columna' => 'nombre_resp',
      'etiqueta' => 'Nombre Resp',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    7 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 160,
      'orden' => '8',
      'columna' => 'cargo_resp',
      'etiqueta' => 'Cargo Resp',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    8 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 161,
      'orden' => '9',
      'columna' => 'equipo_catedra',
      'etiqueta' => 'Equipo Catedra',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    9 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 162,
      'orden' => '10',
      'columna' => 'id_materia_prog',
      'etiqueta' => 'Id Materia Prog',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    10 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 163,
      'orden' => '11',
      'columna' => 'periodo_dictado',
      'etiqueta' => 'Periodo Dictado',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    11 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 164,
      'orden' => '12',
      'columna' => 'ano_academico',
      'etiqueta' => 'Ano Academico',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    12 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 165,
      'orden' => '13',
      'columna' => 'fundamentacion',
      'etiqueta' => 'Fundamentacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    13 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 166,
      'orden' => '14',
      'columna' => 'objetivos',
      'etiqueta' => 'Objetivos',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    14 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 167,
      'orden' => '15',
      'columna' => 'programa_analitico',
      'etiqueta' => 'Programa Analitico',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    15 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 168,
      'orden' => '16',
      'columna' => 'bibliografia',
      'etiqueta' => 'Bibliografia',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    16 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 169,
      'orden' => '17',
      'columna' => 'propuesta_metodologica',
      'etiqueta' => 'Propuesta Metodologica',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    17 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 170,
      'orden' => '18',
      'columna' => 'evaluacion_acreditacion',
      'etiqueta' => 'Evaluacion Acreditacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    18 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 171,
      'orden' => '19',
      'columna' => 'distribucion_horaria',
      'etiqueta' => 'Distribucion Horaria',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    19 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 172,
      'orden' => '20',
      'columna' => 'cronograma_tentativo',
      'etiqueta' => 'Cronograma Tentativo',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    20 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 173,
      'orden' => '21',
      'columna' => 'estado',
      'etiqueta' => 'Estado',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    21 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 174,
      'orden' => '22',
      'columna' => 'observaciones',
      'etiqueta' => 'Observaciones',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    22 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 175,
      'orden' => '23',
      'columna' => 'comentarios',
      'etiqueta' => 'Comentarios',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    23 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 176,
      'orden' => '24',
      'columna' => 'firma_doc',
      'etiqueta' => 'Firma Doc',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    24 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 177,
      'orden' => '25',
      'columna' => 'firma_dto',
      'etiqueta' => 'Firma Dto',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    25 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 178,
      'orden' => '26',
      'columna' => 'firma_sac',
      'etiqueta' => 'Firma Sac',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    26 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 179,
      'orden' => '27',
      'columna' => 'horas_teoricas',
      'etiqueta' => 'Horas Teoricas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 1,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'N',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    27 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 180,
      'orden' => '28',
      'columna' => 'horas_practicas',
      'etiqueta' => 'Horas Practicas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 1,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'N',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    28 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 10,
      'fila' => 181,
      'orden' => '29',
      'columna' => 'horas_teoricopracticas',
      'etiqueta' => 'Horas Teoricopracticas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 1,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'N',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
  ),
);
	}

}

?>