<?php

class toba_mc_comp__2430
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'catedras',
    'objeto' => 2430,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'dt_planificaciones',
    'subclase_archivo' => 'datos/dt_planificaciones.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'planificaciones',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'catedras',
    'fuente' => 'catedras',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2025-03-12 13:02:14',
    'punto_montaje' => 13,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => 13,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'planificaciones',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => 13,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => 0,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => 'public',
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 913,
      'columna' => 'id_planificacion',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => 'planificaciones_id_planificacion_seq',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    1 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 914,
      'columna' => 'ano_acad_planif',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    2 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 915,
      'columna' => 'id_prog_planif',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    3 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 916,
      'columna' => 'equipo_catedra_planif',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    4 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 917,
      'columna' => 'dist_horaria_planif',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    5 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 918,
      'columna' => 'horarios_consulta',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    6 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 919,
      'columna' => 'otras_tareas',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    7 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 920,
      'columna' => 'bibliografia_pedida',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    8 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 921,
      'columna' => 'actividades_internas',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    9 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 922,
      'columna' => 'actividades_externas',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    10 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 923,
      'columna' => 'libros_pub',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    11 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 924,
      'columna' => 'apuntes_pub',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    12 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 925,
      'columna' => 'guia_trabajos_pub',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    13 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 926,
      'columna' => 'publicaciones_periodicas',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    14 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 927,
      'columna' => 'opinion_area',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    15 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 928,
      'columna' => 'opinion_depto',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    16 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 929,
      'columna' => 'observaciones_planif',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    17 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 930,
      'columna' => 'comentarios_planif',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
    18 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2430,
      'col_id' => 951,
      'columna' => 'estado_planificacion',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'planificaciones',
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>