<?php

class toba_mc_comp__17
{
	static function get_metadatos()
	{
		return array (
  'molde' => 
  array (
    'proyecto' => 'catedras',
    'molde' => 17,
    'operacion_tipo' => 10,
    'nombre' => 'Informes',
    'item' => '3491',
    'carpeta_archivos' => 'informes',
    'prefijo_clases' => '_informes',
    'fuente' => 'catedras',
    'clase' => 'toba_asistente_abms',
  ),
  'molde_abms' => 
  array (
    'proyecto' => 'catedras',
    'molde' => 17,
    'tabla' => 'informes',
    'gen_usa_filtro' => 1,
    'gen_separar_pantallas' => 1,
    'cuadro_eof' => NULL,
    'cuadro_id' => 'id_informe',
    'filtro_comprobar_parametros' => 0,
    'cuadro_forzar_filtro' => 0,
    'cuadro_eliminar_filas' => 0,
    'cuadro_carga_origen' => 'datos_tabla',
    'cuadro_carga_sql' => 'SELECT
	t_i.id_informe,
	t_p.apellido_resp as id_prog_informe_nombre,
	t_i.inscriptos,
	t_i.comenzaron,
	t_i.aprobaron,
	t_i.abandonaron,
	t_i.desaprobaron,
	t_i.causas_abandono_desap,
	t_i.caract_grupo,
	t_i.estrategias,
	t_i.consideraciones_interior,
	t_i.analisis_actividades,
	t_i.suficiencia_adecuacion,
	t_i.evaluacion_ays,
	t_i.articulacion,
	t_i.capacitacion,
	t_i.analisis_por_cargo
FROM
	informes as t_i,
	programas as t_p
WHERE
		t_i.id_prog_informe = t_p.id_programa
ORDER BY causas_abandono_desap',
    'cuadro_carga_php_include' => NULL,
    'cuadro_carga_php_clase' => NULL,
    'cuadro_carga_php_metodo' => NULL,
    'datos_tabla_validacion' => NULL,
    'apdb_pre' => NULL,
  ),
  'molde_abms_fila' => 
  array (
    0 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 334,
      'orden' => '1',
      'columna' => 'id_informe',
      'etiqueta' => 'Id Informe',
      'en_cuadro' => 0,
      'en_form' => 0,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => 'informes_id_informe_seq',
      'dt_pk' => 1,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    1 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 335,
      'orden' => '2',
      'columna' => 'id_prog_informe',
      'etiqueta' => 'Id Prog Informe',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id_programa, apellido_resp FROM programas ORDER BY apellido_resp',
      'ef_carga_tabla' => 'programas',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id_programa',
      'ef_carga_col_desc' => 'apellido_resp',
    ),
    2 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 336,
      'orden' => '3',
      'columna' => 'inscriptos',
      'etiqueta' => 'Inscriptos',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    3 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 337,
      'orden' => '4',
      'columna' => 'comenzaron',
      'etiqueta' => 'Comenzaron',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    4 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 338,
      'orden' => '5',
      'columna' => 'aprobaron',
      'etiqueta' => 'Aprobaron',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    5 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 339,
      'orden' => '6',
      'columna' => 'abandonaron',
      'etiqueta' => 'Abandonaron',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    6 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 340,
      'orden' => '7',
      'columna' => 'desaprobaron',
      'etiqueta' => 'Desaprobaron',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    7 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 341,
      'orden' => '8',
      'columna' => 'causas_abandono_desap',
      'etiqueta' => 'Causas Abandono Desap',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    8 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 342,
      'orden' => '9',
      'columna' => 'caract_grupo',
      'etiqueta' => 'Caract Grupo',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    9 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 343,
      'orden' => '10',
      'columna' => 'estrategias',
      'etiqueta' => 'Estrategias',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    10 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 344,
      'orden' => '11',
      'columna' => 'consideraciones_interior',
      'etiqueta' => 'Consideraciones Interior',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    11 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 345,
      'orden' => '12',
      'columna' => 'analisis_actividades',
      'etiqueta' => 'Analisis Actividades',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    12 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 346,
      'orden' => '13',
      'columna' => 'suficiencia_adecuacion',
      'etiqueta' => 'Suficiencia Adecuacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    13 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 347,
      'orden' => '14',
      'columna' => 'evaluacion_ays',
      'etiqueta' => 'Evaluacion Ays',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    14 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 348,
      'orden' => '15',
      'columna' => 'articulacion',
      'etiqueta' => 'Articulacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    15 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 349,
      'orden' => '16',
      'columna' => 'capacitacion',
      'etiqueta' => 'Capacitacion',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    16 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 17,
      'fila' => 350,
      'orden' => '17',
      'columna' => 'analisis_por_cargo',
      'etiqueta' => 'Analisis Por Cargo',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
  ),
);
	}

}

?>