<?php

class toba_mc_comp__16
{
	static function get_metadatos()
	{
		return array (
  'molde' => 
  array (
    'proyecto' => 'catedras',
    'molde' => 16,
    'operacion_tipo' => 10,
    'nombre' => 'abm Planificaciones',
    'item' => '3490',
    'carpeta_archivos' => 'abm_planificaciones',
    'prefijo_clases' => '_abm_planificaciones',
    'fuente' => 'catedras',
    'clase' => 'toba_asistente_abms',
  ),
  'molde_abms' => 
  array (
    'proyecto' => 'catedras',
    'molde' => 16,
    'tabla' => 'planificaciones',
    'gen_usa_filtro' => 1,
    'gen_separar_pantallas' => 1,
    'cuadro_eof' => NULL,
    'cuadro_id' => 'id_planificacion',
    'filtro_comprobar_parametros' => 0,
    'cuadro_forzar_filtro' => 0,
    'cuadro_eliminar_filas' => 0,
    'cuadro_carga_origen' => 'datos_tabla',
    'cuadro_carga_sql' => 'SELECT
	t_p.id_planificacion,
	t_p.ano_acad_planif,
	t_p.id_prog_planif,
	t_p.equipo_catedra_planif,
	t_p.dist_horaria_planif,
	t_p.horarios_consulta,
	t_p.otras_tareas,
	t_p.bibliografia_pedida,
	t_p.actividades_internas,
	t_p.actividades_externas,
	t_p.libros_pub,
	t_p.apuntes_pub,
	t_p.guia_trabajos_pub,
	t_p.publicaciones_periodicas,
	t_p.opinion_area,
	t_p.opinion_depto,
	t_p.observaciones_planif,
	t_p.comentarios_planif
FROM
	planificaciones as t_p
ORDER BY equipo_catedra_planif',
    'cuadro_carga_php_include' => NULL,
    'cuadro_carga_php_clase' => NULL,
    'cuadro_carga_php_metodo' => NULL,
    'datos_tabla_validacion' => NULL,
    'apdb_pre' => NULL,
  ),
  'molde_abms_fila' => 
  array (
    0 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 316,
      'orden' => '1',
      'columna' => 'id_planificacion',
      'etiqueta' => 'Id Planificacion',
      'en_cuadro' => 0,
      'en_form' => 0,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => 'planificaciones_id_planificacion_seq',
      'dt_pk' => 1,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    1 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 317,
      'orden' => '2',
      'columna' => 'ano_acad_planif',
      'etiqueta' => 'Ano Acad Planif',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    2 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 318,
      'orden' => '3',
      'columna' => 'id_prog_planif',
      'etiqueta' => 'Id Prog Planif',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    3 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 319,
      'orden' => '4',
      'columna' => 'equipo_catedra_planif',
      'etiqueta' => 'Equipo Catedra Planif',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    4 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 320,
      'orden' => '5',
      'columna' => 'dist_horaria_planif',
      'etiqueta' => 'Dist Horaria Planif',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    5 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 321,
      'orden' => '6',
      'columna' => 'horarios_consulta',
      'etiqueta' => 'Horarios Consulta',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    6 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 322,
      'orden' => '7',
      'columna' => 'otras_tareas',
      'etiqueta' => 'Otras Tareas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    7 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 323,
      'orden' => '8',
      'columna' => 'bibliografia_pedida',
      'etiqueta' => 'Bibliografia Pedida',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    8 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 324,
      'orden' => '9',
      'columna' => 'actividades_internas',
      'etiqueta' => 'Actividades Internas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    9 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 325,
      'orden' => '10',
      'columna' => 'actividades_externas',
      'etiqueta' => 'Actividades Externas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    10 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 326,
      'orden' => '11',
      'columna' => 'libros_pub',
      'etiqueta' => 'Libros Pub',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    11 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 327,
      'orden' => '12',
      'columna' => 'apuntes_pub',
      'etiqueta' => 'Apuntes Pub',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    12 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 328,
      'orden' => '13',
      'columna' => 'guia_trabajos_pub',
      'etiqueta' => 'Guia Trabajos Pub',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    13 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 329,
      'orden' => '14',
      'columna' => 'publicaciones_periodicas',
      'etiqueta' => 'Publicaciones Periodicas',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    14 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 330,
      'orden' => '15',
      'columna' => 'opinion_area',
      'etiqueta' => 'Opinion Area',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    15 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 331,
      'orden' => '16',
      'columna' => 'opinion_depto',
      'etiqueta' => 'Opinion Depto',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    16 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 332,
      'orden' => '17',
      'columna' => 'observaciones_planif',
      'etiqueta' => 'Observaciones Planif',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    17 => 
    array (
      'proyecto' => 'catedras',
      'molde' => 16,
      'fila' => 333,
      'orden' => '18',
      'columna' => 'comentarios_planif',
      'etiqueta' => 'Comentarios Planif',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => 'ILIKE',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 14,
      'dt_tipo_dato' => 'X',
      'dt_largo' => NULL,
      'dt_secuencia' => NULL,
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_editable_textarea',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
  ),
);
	}

}

?>