<?php

class toba_mc_comp__2308
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'catedras',
    'objeto' => 2308,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'dt_programas',
    'subclase_archivo' => 'datos/dt_programas.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'programas',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'catedras',
    'fuente' => 'catedras',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2024-09-25 17:09:42',
    'punto_montaje' => 13,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => 13,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'programas',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => 13,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => 0,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => 'public',
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 812,
      'columna' => 'id_programa',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    1 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 813,
      'columna' => 'id_designacion',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    2 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 814,
      'columna' => 'id_asignacion',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    3 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 815,
      'columna' => 'legajo_resp',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    4 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 816,
      'columna' => 'dni_resp',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    5 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 817,
      'columna' => 'apellido_resp',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    6 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 818,
      'columna' => 'nombre_resp',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    7 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 819,
      'columna' => 'cargo_resp',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    8 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 820,
      'columna' => 'equipo_catedra',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    9 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 821,
      'columna' => 'id_materia_prog',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    10 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 822,
      'columna' => 'periodo_dictado',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    11 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 823,
      'columna' => 'ano_academico',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    12 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 824,
      'columna' => 'fundamentacion',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    13 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 825,
      'columna' => 'objetivos',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    14 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 826,
      'columna' => 'programa_analitico',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    15 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 827,
      'columna' => 'bibliografia',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    16 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 828,
      'columna' => 'propuesta_metodologica',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    17 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 829,
      'columna' => 'evaluacion_acreditacion',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    18 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 830,
      'columna' => 'distribucion_horaria',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    19 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 831,
      'columna' => 'cronograma_tentativo',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    20 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 832,
      'columna' => 'estado',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    21 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 833,
      'columna' => 'observaciones',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    22 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 834,
      'columna' => 'comentarios',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    23 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 835,
      'columna' => 'firma_doc',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    24 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 836,
      'columna' => 'firma_dto',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    25 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 837,
      'columna' => 'firma_sac',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => NULL,
    ),
    26 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 910,
      'columna' => 'horas_teoricas',
      'tipo' => 'N',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'programas',
    ),
    27 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 911,
      'columna' => 'horas_practicas',
      'tipo' => 'N',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'programas',
    ),
    28 => 
    array (
      'objeto_proyecto' => 'catedras',
      'objeto' => 2308,
      'col_id' => 912,
      'columna' => 'horas_teoricopracticas',
      'tipo' => 'N',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'programas',
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>